name: Baekjoon To Notion

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Notion Script
        env:
          NOTION_API: ${{ secrets.NOTION_API }}
          NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: python -u upload_to_notion.py
